Bundle logstash and java8 packages so the ingestor_cloudfoundry-firehose doesn't depend on the ingestor_syslog job from logsearch-boshrelease

diff --git a/logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl b/logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl
--- a/logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl
+++ b/logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl
@@ -9,31 +9,55 @@ source /var/vcap/jobs/ingestor_cloudfoundry-firehose/helpers/ctl_setup.sh 'inges
 export PORT=${PORT:-5000}
 export LANG=en_US.UTF-8
 
-# Disable IPv6, since this seems to prevent firehose-to-syslog from connecting to ingestor_syslog
-if ! grep -q 'net.ipv6.conf.lo.disable_ipv6 = 1' /etc/sysctl.conf ; then
-   echo "Disabling IPv6..."
-   echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
-   echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
-   echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
-   sysctl -p
-fi
+# 1 logstash worker / CPU core
+export LOGSTASH_WORKERS=`grep -c ^processor /proc/cpuinfo`
 
 case $1 in
 
-  start)
+  start_syslog)
+    echo "Starting Logstash syslog ingestor on 127.0.0.1:514"
 
-    echo "Waiting 5m for syslog server on: <%= p("ingestor_cloudfoundry-firehose.syslog-server")%> to accept connections..."
+    pid_guard $PIDFILE_syslog $JOB_NAME_syslog
+
+    # store this processes pid in $PIDFILE, since the exec below doesn't daemonize
+    echo $$ > $PIDFILE_syslog
+
+    exec /var/vcap/packages/logstash/logstash/bin/logstash agent \
+         -f ${JOB_DIR}/config/syslog_to_redis.conf -w ${LOGSTASH_WORKERS} \
+         >>$LOG_DIR/$JOB_NAME_syslog.stdout.log \
+         2>>$LOG_DIR/$JOB_NAME_syslog.stderr.log
+
+    ;;
+
+  stop_syslog)
+    kill_and_wait $PIDFILE_syslog
+
+    ;;
+
+  start)
+    echo "Starting CF firehose-to-syslog ingestor"
+
+    # Disable IPv6, since this seems to prevent firehose-to-syslog from connecting to logstash
+    if ! grep -q 'net.ipv6.conf.lo.disable_ipv6 = 1' /etc/sysctl.conf ; then
+       echo "Disabling IPv6..."
+       echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
+       echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
+       echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
+       sysctl -p
+    fi
+
+    echo "Waiting 1m for syslog ingestor on: 127.0.0.1:514 to accept connections..."
     n=0
-    until [ $n -ge 60 ]
+    until [ $n -ge 12 ]
     do
-      nc -4 -z -v <%= p("ingestor_cloudfoundry-firehose.syslog-server").gsub(':',' ') %> 2>&1 && break
+      nc -4 -z -v 127.0.0.1 514 2>&1 && break
       n=$[$n+1]
-      echo "Waiting for <%= p("ingestor_cloudfoundry-firehose.syslog-server")%> to accept connections ($n of 60)..."
+      echo "Waiting for 127.0.0.1:514 to accept connections ($n of 12)..."
       sleep 5
     done
 
-    if [ "$n" -ge "60" ]; then
-       echo "ERROR:  Cannot connect to syslog server on: <%= p("ingestor_cloudfoundry-firehose.syslog-server")%>  Exiting..."
+    if [ "$n" -ge "12" ]; then
+       echo "ERROR:  Cannot connect to syslog ingestor on: 127.0.0.1:514  Exiting..."
        exit 1
     fi
 
@@ -48,7 +72,7 @@ case $1 in
         <% if p("ingestor_cloudfoundry-firehose.skip-ssl-validation") %>--skip-ssl-validation <% end %> \
         --user=<%= p("ingestor_cloudfoundry-firehose.firehose-user") %> \
         --password=<%= p("ingestor_cloudfoundry-firehose.firehose-password") %> \
-        --syslog-server=<%= p("ingestor_cloudfoundry-firehose.syslog-server") %> \
+        --syslog-server=127.0.0.1:514 \
         --events=LogMessage,Error,ContainerMetric \
         --boltdb-path=$TMP_DIR/firehose-to-syslog.cache.db \
         --cc-pull-time=60s \<% if p("ingestor_cloudfoundry-firehose.debug") %>
@@ -63,7 +87,7 @@ case $1 in
 
     ;;
   *)
-    echo "Usage: ingestor_cloudfoundry-firehose_ctl {start|stop}"
+    echo "Usage: ingestor_cloudfoundry-firehose_ctl {start|stop|start_syslog|stop_syslog}"
 
     ;;
 
